<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">

    <title>
        USeP School of Law - Final List
    </title>

    <style>
        @page {
            margin: 38px 42px;
        }

        * {
            box-sizing: border-box;
        }

        body {
            margin: 0;
            font-family: DejaVu Sans, sans-serif;
            color: #222222;
            font-size: 12px;
            line-height: 1.5;
        }

        .header {
            border-bottom: 3px solid #691f1f;
            padding-bottom: 16px;
            margin-bottom: 24px;
            text-align: center;
        }

        .school {
            margin: 0;
            color: #691f1f;
            font-size: 20px;
            font-weight: bold;
        }

        .office {
            margin: 5px 0 0;
            color: #555555;
            font-size: 12px;
        }

        .title {
            margin: 22px 0 4px;
            font-size: 18px;
            font-weight: bold;
            color: #222222;
        }

        .subtitle {
            margin: 0;
            color: #666666;
            font-size: 11px;
        }

        .summary {
            margin-bottom: 16px;
            padding: 10px 12px;
            background: #f9eeee;
            border: 1px solid #ead0d0;
            color: #691f1f;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th {
            background: #691f1f;
            color: #ffffff;
            padding: 10px 9px;
            border: 1px solid #691f1f;
            text-align: left;
            font-size: 11px;
        }

        td {
            padding: 10px 9px;
            border: 1px solid #dddddd;
            vertical-align: top;
            font-size: 11px;
        }

        .number {
            width: 42px;
            text-align: center;
        }

        .name {
            width: 42%;
        }

        .email {
            width: auto;
            word-break: break-word;
        }

        .empty {
            text-align: center;
            color: #777777;
            padding: 24px;
        }

        .footer {
            margin-top: 24px;
            padding-top: 12px;
            border-top: 1px solid #dddddd;
            color: #777777;
            font-size: 9px;
            text-align: center;
        }
    </style>
</head>

<body>

    <div class="header">

        <p class="school">
            University of Southeastern Philippines
        </p>

        <p class="office">
            School of Law Admission Portal
        </p>

        <p class="title">
            Final List of Passed Applicants
        </p>

        <p class="subtitle">
            Applicants who passed the admission interview
        </p>

    </div>


    <div class="summary">

        <strong>
            Total Passed Applicants:
        </strong>

        {{ $finalists->count() }}

        <br>

        <strong>
            Generated:
        </strong>

        {{ $generatedAt->format('F j, Y g:i A') }}

    </div>


    <table>

        <thead>
            <tr>
                <th class="number">
                    No.
                </th>

                <th class="name">
                    Applicant Name
                </th>

                <th class="email">
                    Email Address
                </th>
            </tr>
        </thead>


        <tbody>

            @forelse ($finalists as $index => $finalist)

                <tr>

                    <td class="number">
                        {{ $index + 1 }}
                    </td>

                    <td class="name">
                        {{ $finalist->full_name }}
                    </td>

                    <td class="email">
                        {{ $finalist->email }}
                    </td>

                </tr>

            @empty

                <tr>

                    <td
                        colspan="3"
                        class="empty"
                    >
                        No passed applicants are currently available.
                    </td>

                </tr>

            @endforelse

        </tbody>

    </table>


    <div class="footer">
        This document was generated by the USeP School of Law Admission Portal.
    </div>

</body>

</html>
